import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter } from 'next/font/google'
import '@/shared/styles/globals.css'
import { cn } from '@/shared/lib/utils'

import AppProvider from '@/app/(default-layout)/provider'

import { SidebarProvider, SidebarInset } from '@/shared/components/shadcn/ui/sidebar'
import Sidebar from '@/shared/components/shadcn/custom/sidebar'
import Header from '@/shared/components/shadcn/custom/header'
import Footer from '@/shared/components/shadcn/custom/footer'
import { Toaster } from '@/shared/components/shadcn/custom/sonner'

import { getSession } from '@/shared/actions/auth'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()

  return (
    <html
      lang="ko"
      suppressHydrationWarning
      className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProvider>
          <SidebarProvider>
            <Sidebar user={session?.user} />
            <SidebarInset>
              <Header />
              {/* <Wrapper>
                {children}
              </Wrapper> */}
              {children}
              <Toaster
                position="top-center"
                richColors
                expand
                // closeButton
                duration={2000}
                visibleToasts={3}
              />
              <Footer />
            </SidebarInset>
          </SidebarProvider>
        </AppProvider>
      </body>
    </html>
  )
}

function Wrapper({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div className="bg-background w-full">
      <div
        data-slot="example-wrapper"
        className={cn(
          'mx-auto grid min-h-screen w-full max-w-5xl min-w-0 content-center items-start gap-8 p-4 pt-2 sm:gap-12 sm:p-6 md:grid-cols-2 md:gap-8 lg:p-12 2xl:max-w-6xl',
          className
        )}
        {...props}
      />
    </div>
  )
}

function CustomRootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="ko"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        inter.variable
      )}>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  )
}
